# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://neo4dev.github.io/crawler_from_scratch/"

git_url = "https://github.com/neo4dev/crawler_from_scratch/tree/master/"

def custom_doc_links(name): return None
