# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"find_candidate_content_list": "01_Advanced_Request.ipynb",
         "find_content_list": "01_Advanced_Request.ipynb",
         "get_content_list": "01_Advanced_Request.ipynb",
         "is_next_page": "01_Advanced_Request.ipynb",
         "get_next_page_url": "01_Advanced_Request.ipynb",
         "get_childrens": "01_Advanced_Request.ipynb",
         "get_prefix": "01_Advanced_Request.ipynb",
         "get_item_data": "01_Advanced_Request.ipynb",
         "find_item_id": "01_Advanced_Request.ipynb"}

modules = ["utils.py",
           "auto.py"]

doc_url = "https://neo4dev.github.io/crawler_from_scratch/"

git_url = "https://github.com/neo4dev/crawler_from_scratch/tree/master/"

def custom_doc_links(name): return None
