# AUTOGENERATED! DO NOT EDIT! File to edit: 12_Database.ipynb (unless otherwise specified).

__all__ = ['parse_recipe_data', 'get_recipe_data']

# Cell
import redis

# Cell
import requests,json,re,random,sys
from bs4 import BeautifulSoup,Tag,NavigableString

from .proxy import *

from concurrent.futures import ThreadPoolExecutor
import pandas as pd


# Cell
def parse_recipe_data(html):
    data = {}

    soup = BeautifulSoup(html,'lxml')

    data['title'] = soup.find('h1','page-title').text.strip()

    author = soup.find('div','author')
    data['author_link'] = author.a['href']
    data['author_name'] = author.span.text.strip()

    data['created_at'] = soup.find('div','time').span.text.strip()

    data['category'] = soup.find('ol','breadcrumb').find_all('a')[1].text

    if soup.find('div','ings'):
        data['ings'] = [i.text.strip() for i in soup.find('div','ings').find_all('td','name')]

    for s in soup.find_all('span','number'):
        if 'score' in s.parent.attrs['class']: data['score'] = s.text.strip()
        if 'cooked' in s.parent.attrs['class']: data['cooked'] = s.text.strip()

    return data

def get_recipe_data(_id):
    global rdb
    html = rdb.hget('html',_id)
    return parse_recipe_data(html)

